export const START_GAME_CLICKED = "START_GAME_CLICKED";
export const BEGIN_GAME_CLICKED = "BEGIN_GAME_CLICKED";
export const WHO_MOVE_FIRST_CHANGED = "WHO_MOVE_FIRST_CHANGED";

export const SOME_PLAYERS_CARD_CLICKED = "SOME_PLAYERS_CARD_CLICKED";

export const PLAYER_TAKE_CLICKED = "PLAYER_TAKE_CLICKED";
export const AI_TAKE_CLICKED = "AI_TAKE_CLICKED";
export const REMOVE_CARDS_CLICKED = "REMOVE_CARDS_CLICKED";

export const GAME_OVER = "GAME_OVER";