export const START_GAME_CLICKED = 'START_GAME_CLICKED';
export const BEGIN_GAME_CLICKED = 'BEGIN_GAME_CLICKED';
export const WHO_MOVE_FIRST_CHANGED = 'WHO_MOVE_FIRST_CHANGED';

export const PREV_BUTTON_CLICKED = 'PREV_BUTTON_CLICKED';
export const NEXT_BUTTON_CLICKED = 'NEXT_BUTTON_CLICKED';

export const SOME_PLAYERS_CARD_CLICKED = 'SOME_PLAYERS_CARD_CLICKED';

export const PLAYER_TAKE_CLICKED = 'PLAYER_TAKE_CLICKED';